### PR TITLE
Maika 1033

### PR DESCRIPTION
**Pull request by ntran18**
Fixing bottom dataset

### CODE REVIEW

**Comment by ntran18** [comment]
I was able to make the selection in the bottom data menu. However, I'm thinking there is problem with database. One notice problem is that in graph.js, `grnState.workbook.expression[dataset]` not always contains data, it can be a null object. I fixed this one, however, sometimes I choose a random expression, the error shows there is no value `p.length` but doesn't show which files it refer to. I wasn't able to look more on this problem this week because I didn't have time. Will take a look at it again next week.

**Review by dondi — COMMENTED** [review]
Looks like this PR has linter issues—for direct reference, you can look at the Travis report: https://app.travis-ci.com/github/dondi/GRNsight/builds/266145719

You should also be able to do `npm run lint` on the command line in order to see these messages

**Comment by dondi** [comment]
As a side note, these linter errors will be more avoidable if we configure an autoformatter that complies with the current style checks made by the `npm run lint` command. We have an issue for this (#882) which we can bump in priority when the time is right

**Comment by ntran18** [comment]
I expected some errors would happen. However, these errors are out of my scope of understand so I might need to meet with @dondi to discuss about these problems. I also think this is a different issue, related to database, not the UI.  

Problems: When you click in some expressions, especially the one contains ACE node, it would not reflect on the UI, meaning the check doesn't change to your selection. This is because the program can't load the expression. As I mentioned before, this is because there is no value `p.length` (I experienced some expressions, and it happens mostly for ACE node, not sure about the other nodes). However, if you click on that selection again, it works, but I don't know if it is correct or not.

1. Lint errors 
image
image
image
image
--> From what I understand, I think either the version of database I currently have has different expression sheet name. A lot of errors were wrong name, or worksheet not detected. 

2. Example of error from console
image

**Review by dondi — APPROVED** [review]
LGTM from a code perspective; but as noted in #1033 and in the comments, merging these changes appears to reveal an internal error due to missing data

**Pull request merged**
