### PR TITLE
#992 Adding a grnsettings table to database 

### PR DESCRIPTION
**Pull request by ahmad00m**

### CODE REVIEW

**Comment by dondi** [comment]
Suggestions on how to address this error were listed in #992

**Comment by ahmad00m** [comment]
I made a quick fix for the linter issue. I believe this to be a temporary fix as I changed ecmaVersion to v.8 and made `grnsight.js` to ignore it. It passed the checks but please let me know if I should look for a more solid solution.

**Review by dondi — APPROVED** [review]
LGTM—will need to resolve conflicts first, plus be ready to update the beta database upon deployment

**Review by dondi — APPROVED** [review]
LGTM

**Pull request merged**
