### PR TITLE
Species Display

### PR DESCRIPTION
**Pull request by Kevboe**
Properly formatted drop down menu that displays all species for the user to select. This will update the display as well as the GRNstate code which will be used later for API calls. Also has file input detection for species.

### CODE REVIEW

**Comment by dondi** [comment]
@Kevboe Please look at the Travis CI build failures in this PR (you can click on _Details_ then go to the _View more details on Travis CI_ link at the bottom of the page that appears) and address them before we proceed with the PR. I took a peek; they are mostly things like variable names, semicolons, etc. So, should be pretty easy to fix. Thanks!

**Comment by Kevboe** [comment]
I have fixed all the errors that I could in my code. There are some errors that is causing the Travis build to fail. These are either pieces which I did not change, or "not defined errors" which are for pieces of the HTML that I am updating. Let me know what I need to do to fix these.

**Comment by dondi** [comment]
OK @Kevboe I looked at the remaining errors. Here they are for easy reference:
```
/home/travis/build/dondi/GRNsight/web-client/public/js/update-app.js
516  280:11  error  'speciesIdentifiedIcon' is not defined     no-undef
517  281:11  error  'speciesIdentifiedIcon' is not defined     no-undef
518  283:7   error  'speciesIdentifiedIcon' is not defined     no-undef
519  284:7   error  'speciesIdentifiedIcon' is not defined     no-undef
520  363:15  error  'speciesDisplay' is not defined            no-undef
521  538:7   error  'yeastDisplay' is not defined              no-undef
522  538:35  error  Missing space before function parentheses  space-before-function-paren
523  538:37  error  Missing space before opening brace         space-before-blocks
524  543:7   error  'humanDisplay' is not defined              no-undef
525  548:7   error  'fruitflyDisplay' is not defined           no-undef
526  553:7   error  'nematodeDisplay' is not defined           no-undef
527  558:7   error  'mouseDisplay' is not defined              no-undef
528  563:7   error  'cressDisplay' is not defined              no-undef
```

Here are my findings:
* `speciesIdentifiedIcon`—The first appearance of this variable is [in this commit](https://github.com/dondi/GRNsight/commit/3e2891a2e1860c1c887c8ce1d39577bfd3e92264#diff-c280ab130671160d35330f345e8bf20a) on the Kev-Species-Display branch. As far as I can tell, it has _never_ been defined. Not sure what testing revealed when you were running this code, but I would have expected errors at runtime.
* `speciesDisplay` is also introduced in that same commit (line 331 of _update-app.js_). Again I see no sign of this variable in preceding code. So the mystery remains regarding why this code worked for you before—it never would have.
* `yeastDisplay` is the same story: it is in that same commit above, on line 508
* The missing space errors are exactly that: the code says `function(){` when it should be `function () {`
* `humanDisplay`, `fruitFlyDisplay`, `nematodeDisplay`, `mouseDisplay`, and `cressDisplay` are all the same story: all introduced in that same past commit

Here’s my guess: you added those same IDs to the Jade/Pug code. _Those IDs are not visible in JavaScript_. They have to be accessed with selector strings (e.g., `"#yeastDisplay"`). Maybe that’s where the misunderstanding lies?

Let me know if this helps.

**Comment by Kevboe** [comment]
Pushed and the only error I see is a variable that is defined and not used. This is from a piece of the code that was updated by @dondi I believe, but since it is out of my realm of work I am leaving it for the time being.

**Comment by kdahlquist** [comment]
@Kevboe "since it is out of my realm of work I am leaving it for the time being."

This error is blocking the pull request, so you should track it down and fix it.  You are on the GRNsight _team_ and our team's goal is to have a fully functional program to release by the end of the semester.  If your feature is done, but we can't release because of bugs, then you didn't actually finish your work.

**Comment by dondi** [comment]
@Kevboe I looked at the error—and yes, even though it doesn’t involve your changes directly, by the nature of the error, I think it is something you can definitely fix. And don’t worry, if there’s a side effect where something else goes wrong (functionally), then we can fix it then. Such is the nature of software development.

But the error as a blocker of Travis can definitely fixed easily.

**Comment by Kevboe** [comment]
Not sure where to leave the description, so I am putting it here for now, and can move it where it needs to be.
This update to the beta added the ability for GRNsight to read in the species and taxon data from a GRNmap workbook. The program is then able to update variables in the GRNstate in preparation for the API call species expansion. The program defaults to yeast, but currently handles humans, mice, fruit flies, nematodes, and the cress as well. To support the species expansion I also added a button/drop down menu that will allow the user to select and update the detected species at any time. Additionally I added an indicator that showed if the species had been detected by the program or by user input.

**Pull request merged**
