### PR TITLE
Gene Pages Pull Request

### PR DESCRIPTION
**Pull request by johnllopez616**
This is the pull request to merge beta with the changes I made for the gene pages in my branch.

### CODE REVIEW

**Comment by johnllopez616** [comment]
Pull Request Checklist
- [ ] Travis C.I. Build Passes
- [ ] All Loaded Demos look as Expected
- [ ] Reload works as expected
- [ ] Loading File with Error brings up error modal, and it looks as expected
- [ ] Loading File with Warning brings up warnings modal
- [ ] Viewport Option Changing works as expected
- [ ] Viewport Size Changing works as expected
- [ ] Hide/Show Weights works as expected
- [ ] Force Sliders change the number above them and have an effect on the graph
- [ ] Locking/Unlocking/Resetting/Undoing the force graph parameters works as expected
- [ ] Weighted graph loaded with the "default to black edges" option checked appears as expected
- [ ] Import works for both SIF and GraphML
- [ ] Graph can be exported to SIF and GraphML

**Comment by johnllopez616** [comment]
To do: 
[] Run ES Lint

**Comment by dondi** [comment]
@johnllopez616 Please see the overall code review and the comment that is attached to the _onlysidebar.html_ file. There is some noise to resolve with this PR first, after which I have then outlined to steps for how to tackle the header and sidebar `iframe`s.

**Comment by dondi** [comment]
Sounds good @johnllopez616, let's revisit this after the document glitches are resolved. The prime characteristic of a valid pull request is that the changes it lists correspond _exactly_ to the changes you made for a particular unit of work. Anything that diverges from that is worth examining.

**Comment by kdahlquist** [comment]
@johnllopez616 says that the document issues have been cleaned up. @dondi--does this resolve your issues with merging this?  It seems like you have outlined additional work to be done after this PR is accepted.

**Comment by dondi** [comment]
My last recollection of this PR is that @johnllopez616 was supposed to go over it with @eileenchoe and @yshin4 to fix the commit glitches that were encountered a few weeks ago (the one that lost homework uploads). Was this done? I don't see any commits indicating that this was fixed.

**Comment by mihirsamdarshi** [comment]
@dondi that was my mistake, it must have happened when I accidentally deleted beta instead of my branch for a hot second

**Comment by dondi** [comment]
It looks like a merge of `beta` into your branch is called for again (in order to capture the latest revisions made before releasing version 3.0.0). Therefore:
`git checkout beta`
`git pull`
`git checkout johnlopez`
`git merge beta`

......Resolve conflicts then _test this version thoroughly_ and before committing it.

**Comment by dondi** [comment]
There are some questionable deletions in this PR. For example: documents/manuscripts/peerj-computerscience-2016/GRNsight_PeerJ-CS_manuscript_2016.docx

That file exists in master. Merging this PR will remove that. Doesn't sound right to me.

**Comment by dondi** [comment]
Sorry for the delay @johnllopez616 @kdahlquist —this PR was showing deleted files that should not have been deleted, mainly in the `documents` folder, and I wanted to track down the reason for this despite my previous impression that the mysterious file disappearance of Spring 2018 had been resolved.

I have finally tracked down the issue, and it turns out that a commit _during the BioDB course_ was actually what deleted these files. The commit can be seen here:

https://github.com/dondi/GRNsight/commit/9ff5c6c590c497085e73cdb18bef024b5d079623

Whatever the intent of that commit might have been, it should not have touched the _documents_ folder at all. Here is another case where a committer was not fully cognizant of the files that were being altered from a commit, and inadvertently changed files that should not have changed.

Unfortunately, there _are_ changes that we want to keep from this commit. I am currently working on a way to both undo this commit but preserve these changes. Will post updates as they occur. But I just wanted to document the reason for this late-breaking issue.

**Comment by dondi** [comment]
"Files changed" went from 57 to 16, solely by undoing a single commit....phew, that is looking much better.

I ran this branch locally and a spot test showed identical behavior with `master`, plus the gene page functionality appears to work. I think we can finally merge.

**Pull request merged**
