### PR TITLE
Gene Page Changes Made Today

### PR DESCRIPTION
**Pull request by johnllopez616**
Addresses Issues #605 #606 #607

### CODE REVIEW

**Comment by johnllopez616** [comment]
Pull Request Checklist
- [ ] Travis C.I. Build Passes
- [ ] All Loaded Demos look as Expected
- [ ] Reload works as expected
- [ ] Loading File with Error brings up error modal, and it looks as expected
- [ ] Loading File with Warning brings up warnings modal
- [ ] Viewport Option Changing works as expected
- [ ] Viewport Size Changing works as expected
- [ ] Hide/Show Weights works as expected
- [ ] Force Sliders change the number above them and have an effect on the graph
- [ ] Locking/Unlocking/Resetting/Undoing the force graph parameters works as expected
- [ ] Weighted graph loaded with the "default to black edges" option checked appears as expected
- [ ] Import works for both SIF and GraphML
- [ ] Graph can be exported to SIF and GraphML

**Comment by mihirsamdarshi** [comment]
Generally we don't create a pull request until we are finished/close to finished with a feature, lets hold off on this until you think that it is wholly ready

**Comment by kdahlquist** [comment]
Actually, I think for the sprint, we can relax that rule.  As long as nothing is broken, I think it's OK to submit the pull request.  Also, it makes sense that we might have a pull request at the end of the day so that we can look at small changes as @dondi requested.

Right now, I can't look at anything new unless it's up on beta, so we need to go through this process so I can test changes.

**Comment by kdahlquist** [comment]
@johnllopez616 told me that he made all the changes requested by @dondi.  I said to go ahead and accept this PR and get the changes live on beta so that I can review and give the next round of feedback.

**Comment by dondi** [comment]
@kdahlquist @johnllopez616 I went ahead and approved this since the style tweaks do not hinder functionality. However @johnllopez616 please note that when we look at code style, the idea is to apply it _universally_. There were some spots where there were alternating lines of style adherence and divergence—try to increase your sensitivity to those. Don't just fix the parts you were directly told to fix.

Along related lines, see what you can do to get your tools to automate this for you as much as possible. Style is important but it should not be a time sink.

**Pull request merged**
