### PR TITLE
Issues #905, #888, #804

### LINKED ISSUE #905: Log Fold Change Max value selection on sidebar has issues
On @igreen1 machine (Firefox 84.0.2, Ubuntu 20.04), the Log Fold Change Max value selection on the sidebar does not work. It does, however, work on the dropdown (Node ->  Log Fold Change Max Value). This issue exists even after every single extensions was removed from @igreen1's browser (including the seemingly unrelated ones)

image

This is possibly linked to the lack of a 'set' button. On @dondi's machine there is an additional 'set' button next to the input value. This issue requires additional help in replication to find where the bug lies.

No relevant web console output was logged on page load. @igreen1 will try to replicate this issue on Windows Firefox and on Windows Edge/Chrome.

### PR DESCRIPTION
**Pull request by igreen1**
Summary changelog:
grnsight.styl changed to fix #905 by reducing size of button so overflow is unnecessary
Changed button direction for #888 by moving camera in opposite direction (flipping signs)
Changed restrict graph to viewport behaviour in #804. Now when restrict-graph is chosen, movement controls are not available and zoom is locked to 100%.

Pull Request Checklist
- [x] Travis C.I. build passes
- [ ] All four Demos look as expected when loaded
- [x] Reload works as expected
- [x] Loading file with Error brings up error modal, and it looks as expected
- [x] Loading file with Warning brings up warnings modal
- [x] Import works for both SIF and GraphML
- [x] Graph can be exported to SIF and GraphML
- [x] Print works as expected
- [x] Restrict graph to viewport works as expected (check/uncheck)
- [x] Viewport Size Changing works as expected (small/medium/large/fit)
- [x] Toggle between Grid Layout and Force Graph Layout works as expected
- [x] Force Graph Parameter Sliders change the number above them and have an effect on the graph
- [x] Locking/Unlocking/Resetting/Undo Resetting the force graph parameters works as expected
- [x] Enabling and disabling node coloring works as expected
- [ ] Node coloring options work as expected (selection top/bottom dataset, averaging values, changing max value)
- [x] Weighted graph loaded with the "default to black edges" option checked appears as expected
- [x] Hide/Show Weights works as expected (always/never/upon mouseover)
- [x] Edge Weight Normalization Factor can be changed (set/reset)
- [x] Gray Edge Threshold can be changed, slider changes the number and has an effect on the graph
- [x] Checking Show Gray Edges as Dashed works as expected (check/uncheck)
- [x] D-pad left/right/top/bottom/center works as expected
- [x] Zoom slider changes number and has effect on graph (viewport and menu)
- [x] Right click on a node opens gene page, page is populated with correct data

### CODE REVIEW

**Review by dondi — APPROVED** [review]
LGTM

**Comment by dondi** [comment]
Ready for checklisting. Please notify @dondi when ready merge.

**Comment by ahmad00m** [comment]
The demos worked as expected at first but after a while the nodes would start moving further apart from one another. Also, the higher number of nodes the more nodes would move apart instead of reaching equilibrium and stopping. Moreover, I noticed some of the options in Top/Bottom Dataset in Node column did not appear on the graph and it showed a message saying "Expression Database is loading".

**Comment by igreen1** [comment]
good catch @ahmad00m that was an interesting bug. the `center` function calls a restart on the simulation. In fact, looking at beta, @igreen1  was able to produce a similar bug by toggling 'restrict graph to viewport'. It causes the nodes to jostle for a long period of time.

This bug can be fixed by removing the restart of simulation in the center command, which does not appear to affect the simulation at all. This will be issued in a commit shortly

**Comment by igreen1** [comment]
Second commit should make it impossible to highlight for all computer types: commit d4e224950cf9dc27a4c863cfa684f0e5a1fd7ffa

@dondi should I add this 'no-highlight' to nodes as well? I'm editing the file anyways.


@igreen1 have been unable to find the reasoning behind the expression database error; however, it happens on the beta branch too so likely a result of needing access, which only the official website has. Will confirm in meetign

**Comment by dondi** [comment]
@dondi will look into network/access restrictions to verify whether the external expression database requests are behaving as expected.

**Review by dondi — APPROVED** [review]
LGTM

**Comment by dondi** [comment]
There are some loose-end checkboxes in this PR but I’ll go ahead and merge and we can seek to resolve those as standalone issues.

**Pull request merged**
