### PR TITLE
Gene Page Changes Made 5/23/2018

### PR DESCRIPTION
**Pull request by johnllopez616**
Addresses the following issues in #620 

- [x] Let's make the hyperlinks on the page to be the main green GRNsight color, instead of multi-colored.  The buttons and section headers look nice with the different colors, but I think to be clear, the rest of the hyperlinks should just be the main GRNsight green color.  This affects both the General and Sources sections.
- [x] Let's use the Wikipedia convention of putting the source citations in square brackets like this <sup>[1]</sup>.
- [x] Let's make the source citations in the square brackets link to the sources section (like a Wikipedia page does).
- [x] In the Sources section, please move the list of citations over to the left-hand side, with the same margin as the other sections above it.
- [x] Let's regularize the font size and bolding for all the sections.  For example, in the regulation section, the field names are not bolded, in the protein section the font is really large.  Whatever the size they are in the general section is good (and bolded).
- [x] The protein sequence is not displaying correctly.  It has a leading space that should be removed and there are line breaks in the sequence that are not being respected when the window is maximized.
- [x] In the general section, it is "NCBI Gene ID" not just "NCBI ID".  NCBI has a lot of different databases and the one we are calling is the "Gene" Database.
- [x] The Jaspar sequence logo image and matrix need to be moved a little to the right.  The matrix is actually overlapping the edge of the section on the left-hand side.
- [x] Can the Jaspar sequence logo image be made a little smaller?

### CODE REVIEW

**Comment by johnllopez616** [comment]
Pull Request Checklist
- [ ] Travis C.I. build passes
- [ ] All four Demos look as expected when loaded
- [ ] Reload works as expected
- [ ] Loading file with Error brings up error modal, and it looks as expected
- [ ] Loading file with Warning brings up warnings modal
- [ ] Import works for both SIF and GraphML
- [ ] Graph can be exported to SIF and GraphML
- [ ] Print works as expected
- [ ] Restrict graph to viewport works as expected (check/uncheck)
- [ ] Viewport Size Changing works as expected (small/medium/large/fit)
- [ ] Toggle between Grid Layout and Force Graph Layout works as expected
- [ ] Force Graph Parameter Sliders change the number above them and have an effect on the graph
- [ ] Locking/Unlocking/Resetting/Undo Resetting the force graph parameters works as expected
- [ ] Enabling and disabling node coloring works as expected
- [ ] Node coloring options work as expected (selection top/bottom dataset, averaging values, changing max value)
- [ ] Weighted graph loaded with the "default to black edges" option checked appears as expected
- [ ] Hide/Show Weights works as expected (always/never/upon mouseover)
- [ ] Edge Weight Normalization Factor can be changed (set/reset)
- [ ] Gray Edge Threshold can be changed, slider changes the number and has an effect on the graph
- [ ] Checking Show Gray Edges as Dashed works as expected (check/uncheck)
- [ ] D-pad left/right/top/bottom/center works as expected
- [ ] Zoom slider changes number and has effect on graph (viewport and menu)

**Comment by mihirsamdarshi** [comment]
@johnllopez616 is something like this supposed to happen? Also can we consider using the same sans serif font that the rest of GRNsight is using?
screen shot 2018-05-23 at 3 30 48 pm

**Comment by kdahlquist** [comment]
To respond to @mihirsamdarshi's comment, I thought we were using the same sans serif font that the rest of GRNsight is using, or am I missing something.  That got changed earlier, right?

**Comment by johnllopez616** [comment]
@kdahlquist @mihirsamdarshi The actual content on the gene page does not. I will make this change.

**Pull request merged**
