### PR TITLE
#1147 include npm lint 

### PR DESCRIPTION
**Pull request by akaiap**
Regarding #1147 -- Includes `npm lint` in the GitHub Action CI script.  Running the lint checker will help catch formatting issues on an ongoing basis.

### CODE REVIEW

**Comment by akaiap** [comment]
The job failed due to two errors in the setup-handlers.js file:

Line 117: Trailing spaces are not allowed.
Line 137: Missing semicolon.

`npm lint` works!

**Review by dondi — COMMENTED** [review]
Looks good, and pleasant surprise there with the lint output integration! As mentioned in the meeting, let’s go ahead and simulate an “error-and-fix” cycle by having you fix the lint errors on this branch, then we can merge

**Comment by akaiap** [comment]
Corrected the trailing spaces and missing the semicolon in web-client/public/js/setup-handlers.js, according `npm lint`.

**Review by dondi — APPROVED** [review]
LGTM 👌🏽

**Pull request merged**
