### PR TITLE
Issue #1083 When check restrict graph to viewport the D-pad and zoom slider do not disappear and graph cannot exceed viewport

### PR DESCRIPTION
**Pull request by ceciliazaragoza**
When restrict graph to viewport all *nodes*, not edges, are restricted to viewport. Graph does not exceed viewport even when dragged, zoomed, or moved with Dpad.

### CODE REVIEW

**Comment by ceciliazaragoza** [comment]
Pull Request Checklist
- [ ] Travis C.I. build passes
- [ ] All five Demos look as expected when loaded
- [ ] Reload works as expected
- [ ] Loading file with Error brings up error modal, and it looks as expected
- [ ] Loading file with Warning brings up warnings modal
- [ ] Loading a network from the database looks as expected when loaded
- [ ] Import works for both SIF and GraphML
- [ ] Graph can be exported to SIF, GraphML and Excel
- [ ] Graph can be exported to PNG, SVG and PDF
- [ ] Expression data and Additional Sheets can be exported to Excel
- [ ] Print works as expected
- [ ] Restrict graph to viewport works as expected (check/uncheck)
- [ ] Viewport Size Changing works as expected (small/medium/large/fit)
- [ ] Toggle between Grid Layout and Force Graph Layout works as expected
- [ ] Force Graph Parameter Sliders change the number above them and have an effect on the graph
- [ ] Locking/Unlocking/Resetting/Undo Resetting the force graph parameters works as expected
- [ ] Enabling and disabling node coloring works as expected
- [ ] Node coloring options work as expected (selection top/bottom dataset, averaging values, changing max value)
- [ ] Weighted graph loaded with the "Enable Edge Coloring" option checked appears as expected
- [ ] Hide/Show Weights works as expected (always/never/upon mouseover)
- [ ] Edge Weight Normalization Factor can be changed (set/reset)
- [ ] Gray Edge Threshold can be changed, slider changes the number and has an effect on the graph
- [ ] Checking Show Gray Edges as Dashed works as expected (check/uncheck)
- [ ] D-pad left/right/top/bottom/center works as expected
- [ ] Zoom slider changes number and has effect on graph (viewport and menu)
- [ ] Right click on a node opens gene page, page is populated with correct data

**Comment by ceciliazaragoza** [comment]
- [ ] All five Demos look as expected when loaded
- Currently when enable restrict to viewport on one demo and then switch to another demo with restrict to viewport still enabled, cannot view the new demo.

**Review by dondi — COMMENTED** [review]
Great to see this come to fruition! Pretty much there; just need to do a tiny bit of modernization when parsing numbers, see individual comments…

**Review by dondi — APPROVED** [review]
Yay thank you!

**Comment by dondi** [comment]
Deploy as you see fit 😊

**Comment by ceciliazaragoza** [comment]
- [ ] D-pad left/right/top/bottom/center works as expected
- D-pad was not being restricted properly, so I had to adjust one line of the code because in `move` function I did not call the viewportBoundsMoveDrag function and instead just had an if statement that said `if ((graphZoom, moveWidth, moveHeight))`. Updated code to `if (viewportBoundsMoveDrag(graphZoom, moveWidth, moveHeight))` and now D-pad is being restricted as expected. I will issue another PR to fix this.

**Pull request merged**
