### PR TITLE
Continue with #1079, fixing the export for sif and make the variable consistent with other files

### PR DESCRIPTION
**Pull request by ntran18**
Fixing the export sif file, and changing networkMode variable to workbookType to match with other custom workbook, easier for exporting.

Pull Request Checklist
- [x] Travis C.I. build passes
- [x] All five Demos look as expected when loaded
- [x] Reload works as expected
- [x] Loading file with Error brings up error modal, and it looks as expected
- [x] Loading file with Warning brings up warnings modal
- [x] Loading a network from the database looks as expected when loaded
- [x] Import works for both SIF and GraphML
- [x] Graph can be exported to SIF, GraphML and Excel
- [x] Graph can be exported to PNG, SVG and PDF
- [x] Expression data and Additional Sheets can be exported to Excel
- [x] Print works as expected
- [x] Restrict graph to viewport works as expected (check/uncheck)
- [x] Viewport Size Changing works as expected (small/medium/large/fit)
- [x] Toggle between Grid Layout and Force Graph Layout works as expected
- [x] Force Graph Parameter Sliders change the number above them and have an effect on the graph
- [x] Locking/Unlocking/Resetting/Undo Resetting the force graph parameters works as expected
- [x] Enabling and disabling node coloring works as expected
- [x] Node coloring options work as expected (selection top/bottom dataset, averaging values, changing max value)
- [x] Weighted graph loaded with the "Enable Edge Coloring" option checked appears as expected
- [x] Hide/Show Weights works as expected (always/never/upon mouseover)
- [x] Edge Weight Normalization Factor can be changed (set/reset)
- [x] Gray Edge Threshold can be changed, slider changes the number and has an effect on the graph
- [x] Checking Show Gray Edges as Dashed works as expected (check/uncheck)
- [x] D-pad left/right/top/bottom/center works as expected
- [x] Zoom slider changes number and has effect on graph (viewport and menu)
- [x] Right click on a node opens gene page, page is populated with correct data

### CODE REVIEW

**Review by dondi — COMMENTED** [review]
Code generally looks good but the change from `networkMode` to `workbookType` may run deep so let’s consider this to be tentatively approved but pending verification of the pull request checklist

**Comment by dondi** [comment]
@ntran18 pointed out some old files under test-files/import-samples that have errors when importing into current code. These appear to be very early attempts at export code and can likely be ignored or deleted

@dondi can look at the overall folder and submit a README to put the files in context

**Comment by ntran18** [comment]
After going through the PR checklist, importing new files has some delays. For example, if you load an error file, and you want to reload another file. It still shows the previous error file, which needs to be re-uploaded. I would say this is a new bug, because I have seen this problem many times, not for this pull request specifically.

**Comment by dondi** [comment]
Clarification from @ntran18 about the error state—this looks unrelated to this issue/PR plus is pre-existing because it is also seen in `master`

**Comment by dondi** [comment]
We did a quick search for the pre-existing issue but it appears to not be previously reported. @ntran18 will write a new issue to describe the behavior and we can add this to our queue of bugs to fix

**Review by dondi — APPROVED** [review]
LGTM

**Pull request merged**
