### PR TITLE
fix #906

### LINKED ISSUE #906: Node colouring dropdown not properly checking/unchecking
From the Node dropdown menu, when 'Enable Node Coloring' is selected, the selection will remain checked, despite Node Coloring turning off. The sidebar 'Enable Node Coloring' will also remain checked. However, selecting the 'Enable Node Color' on the sidebar will properly update the checked state.

It appears then, that the 'checked' property is not properly updated when using Dropdown menu: Node -> Enable Node Coloring. 

The dropdown looks like this regardless of state/input/graph:
image

### PR DESCRIPTION
**Pull request by mihirsamdarshi**
Somehow the case for disabling node coloring got lost while adding expression databases. I also removed a seemingly unused variable that circumvented `grnState`. I am unsure what the CI error is about, I assume its a wrong test file that I have?

### CODE REVIEW

**Comment by dondi** [comment]
Build is failing do to a failed `npm test`—looks like the same issue as in #909, need to track down.

**Comment by mihirsamdarshi** [comment]
`npm run test` works on my end, I am unsure why the build is failing

**Comment by dondi** [comment]
I suspect there might have been a missed pull or a non-updated library on your local clone—I merged beta back into your branch and the build appears to have passed now.

**Review by dondi — APPROVED** [review]
LGTM on a code level; will need to verify in testing

**Pull request merged**
